In [1]:
import torch
import torch.nn as nn


In [2]:
rnn = nn.GRU(10, 20, 2)
input_ = torch.randn(6, 3, 10) # (seq_len, batch, input_state)
h0 = torch.randn(2, 3, 20)
c0 = torch.randn(2, 3, 20)
output, (hn, cn) = rnn(input_)

In [3]:
output.shape

torch.Size([6, 3, 20])

In [4]:
m = nn.AdaptiveMaxPool1d(8, return_indices=True)
input_ = torch.randn(10, 64, 5)
output = m(input_[:,:,-1])
print(output[1].unsqueeze(-1).shape)

torch.Size([10, 8, 1])


In [5]:
input_[:,:,:-1]

tensor([[[-1.5429,  0.6340,  0.0213, -0.4398],
         [-1.2478,  0.2702, -0.4008, -0.6441],
         [ 0.0443,  1.0501,  0.6601,  0.6121],
         ...,
         [ 0.1865, -1.7181,  0.1042,  0.8765],
         [-1.0143,  0.4232,  1.6150, -1.8313],
         [-0.1361,  0.6981, -0.3277, -1.4996]],

        [[ 0.6629, -1.7376, -1.8748, -0.5592],
         [-0.7976, -0.0771,  0.2584, -0.3644],
         [ 0.7348, -1.0431, -1.0107, -1.0151],
         ...,
         [ 0.7027, -0.7950,  0.6436,  0.0942],
         [-1.1621, -0.7787,  0.2876,  1.0734],
         [-1.3584,  1.2312,  1.5533,  1.2621]],

        [[-0.7100, -1.6533, -1.3300, -0.8893],
         [-1.2117,  0.3162,  2.2641,  0.2942],
         [ 1.0777,  0.6341, -0.2230, -0.8033],
         ...,
         [ 0.1786, -0.4029, -1.6282, -0.2730],
         [-0.5307,  0.2570,  0.8143, -0.4049],
         [-0.0122,  0.1454,  0.3424, -0.0264]],

        ...,

        [[-0.2174, -0.2704, -0.7285,  1.3974],
         [ 0.3481,  1.2417, -0.4331, -0.3122]

In [6]:
word_indices = output[1]
word_indices

tensor([[ 5, 10, 23, 30, 34, 46, 54, 60],
        [ 1, 10, 17, 31, 36, 44, 50, 57],
        [ 3, 12, 19, 28, 32, 46, 52, 63],
        [ 6,  8, 16, 28, 36, 41, 54, 56],
        [ 4,  8, 23, 30, 39, 41, 52, 61],
        [ 4, 14, 20, 26, 39, 46, 53, 56],
        [ 0, 13, 19, 27, 34, 47, 53, 58],
        [ 7, 13, 20, 26, 39, 40, 52, 57],
        [ 7, 13, 23, 24, 36, 40, 52, 60],
        [ 2, 14, 23, 26, 34, 43, 54, 56]])

In [7]:
word_indices.unsqueeze(-1).expand(-1,-1,4)

tensor([[[ 5,  5,  5,  5],
         [10, 10, 10, 10],
         [23, 23, 23, 23],
         [30, 30, 30, 30],
         [34, 34, 34, 34],
         [46, 46, 46, 46],
         [54, 54, 54, 54],
         [60, 60, 60, 60]],

        [[ 1,  1,  1,  1],
         [10, 10, 10, 10],
         [17, 17, 17, 17],
         [31, 31, 31, 31],
         [36, 36, 36, 36],
         [44, 44, 44, 44],
         [50, 50, 50, 50],
         [57, 57, 57, 57]],

        [[ 3,  3,  3,  3],
         [12, 12, 12, 12],
         [19, 19, 19, 19],
         [28, 28, 28, 28],
         [32, 32, 32, 32],
         [46, 46, 46, 46],
         [52, 52, 52, 52],
         [63, 63, 63, 63]],

        [[ 6,  6,  6,  6],
         [ 8,  8,  8,  8],
         [16, 16, 16, 16],
         [28, 28, 28, 28],
         [36, 36, 36, 36],
         [41, 41, 41, 41],
         [54, 54, 54, 54],
         [56, 56, 56, 56]],

        [[ 4,  4,  4,  4],
         [ 8,  8,  8,  8],
         [23, 23, 23, 23],
         [30, 30, 30, 30],
         [39, 39, 39

torch.Size([10, 8, 4])

In [18]:
torch.gather(input_[:,:,-1], 1, word_indices).unsqueeze(-1).expand(-1,-1,4).shape

torch.Size([10, 8, 4])

In [21]:
input_[:,:,-1]

tensor([[-9.2207e-01, -7.6410e-01, -1.7134e-01, -5.0198e-01, -1.2302e-01,
          8.9560e-01, -3.1077e-01,  8.1662e-01,  1.0444e+00, -1.1493e+00,
          1.0750e+00,  7.1342e-01, -5.0384e-01, -8.5118e-01,  5.0761e-01,
         -1.0920e+00, -7.6868e-01, -9.4253e-01, -4.0371e-01, -3.6936e-01,
          4.1913e-01,  9.9482e-01, -5.6367e-01,  2.0912e+00,  3.1208e-01,
         -2.0521e-02, -3.5424e-01,  9.6812e-01, -7.6067e-01, -1.2391e-01,
          1.6624e+00, -3.0700e-01, -2.9141e-01,  1.0921e+00,  2.2300e+00,
         -2.8275e-01,  2.5497e-02,  3.1896e-01, -1.5411e+00, -3.4351e-01,
          3.4437e-01, -3.3186e-01, -1.0089e-01,  8.0577e-01,  8.7644e-01,
         -1.3401e+00,  1.0617e+00,  4.5645e-01, -1.6119e+00,  4.3361e-01,
         -9.6377e-01, -6.0172e-01, -1.2605e-01,  1.2165e+00,  1.4890e+00,
          4.9933e-01,  1.1439e-01, -1.9539e+00,  4.8629e-01, -9.7221e-01,
          6.2243e-01, -3.7639e-01,  2.7205e-01, -1.2709e+00],
        [-1.1877e+00,  2.4376e-01, -1.0390e-01, -4

In [29]:
m(input_[:,:-1,-1] - input_[:,1:,-1])[1]

tensor([[ 5,  8, 23, 30, 34, 44, 47, 56],
        [ 1, 11, 17, 31, 36, 44, 50, 59],
        [ 0, 13, 23, 23, 38, 46, 52, 55],
        [ 6,  8, 19, 30, 36, 39, 54, 58],
        [ 4,  8, 18, 24, 32, 41, 48, 55],
        [ 4, 15, 18, 26, 36, 46, 54, 56],
        [ 1, 13, 22, 27, 31, 47, 47, 60],
        [ 7, 13, 20, 26, 31, 47, 47, 57],
        [ 7,  7, 18, 26, 36, 40, 50, 60],
        [ 2, 14, 23, 23, 34, 41, 52, 56]])

In [ ]:
torch.gather(input_diff > threshold)

In [61]:
torch.LongTensor([107]*)

tensor([107])

In [73]:
nn.ConstantPad2d((1, 0, 0, 0,), 0)(input_[:,:-1,-1]).shape

torch.Size([10, 64])

In [74]:
input_[:,:-1,-1].shape

torch.Size([10, 63])

In [76]:
diff = nn.ConstantPad2d((1, 0, 0, 0,), 0)(input_[:,:-1,-1]) - input_[:,:,-1]
threshold = 0
torch.where(diff > threshold, 1, 0).shape

torch.Size([10, 64])

In [65]:
torch.where(diff > threshold, 1, 0)

tensor([[0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
         1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
         0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1],
        [0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
         0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
         0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0],
        [1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
         0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
         0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0],
        [1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
         0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1,
         0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0],
        [0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
         1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 

In [59]:
where[1][where[0] == batch_idx]

tensor([ 2,  4,  5,  9, 11, 12, 14, 16, 17, 19, 21, 23, 24, 26, 27, 28, 31, 32,
        34, 36, 37, 41, 43, 45, 48, 52, 54, 56, 59, 61, 62])

In [62]:
torch.where(diff > threshold)

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3,
         3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
         3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
         4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
         5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6,
         6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
         7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
         7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
         8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9,
         9, 9, 9, 9, 9, 9, 9

In [83]:
zip(torch.where(diff > threshold))

In [84]:
input_[zip(torch.where(diff > threshold))].shape

IndexError: only integers, slices (`:`), ellipsis (`...`), None and long or byte Variables are valid indices (got zip)