In [1]:
import torch
import torch.nn as nn
import numpy as np

In [2]:
rnn = nn.LSTM(10, 20, bidirectional=True)
input_ = torch.randn(6, 3, 10) # (seq_len, batch, input_state)
output, (hn, cn) = rnn(input_)

In [3]:
output.shape

torch.Size([6, 3, 40])

In [4]:
m = nn.AdaptiveMaxPool1d(8, return_indices=True)
input_ = torch.randn(10, 64, 5)
output = m(input_[:,:,-1])
print(output[1].unsqueeze(-1).shape)

torch.Size([10, 8, 1])


In [5]:
input_[:,:,:-1]

tensor([[[-2.5338e-01,  5.4671e-01, -2.3050e-01, -7.2926e-01],
         [ 1.1752e-03,  1.1226e+00,  3.1501e-01,  7.7106e-01],
         [ 4.1628e-01, -1.0956e+00,  9.3177e-01,  1.1895e+00],
         ...,
         [-8.7740e-01, -7.5359e-01, -3.8453e-02, -1.2326e+00],
         [ 4.4664e-01,  6.0821e-01,  1.4042e+00, -3.1158e-01],
         [-2.1279e-01,  3.8654e-01, -8.8885e-01,  7.6134e-01]],

        [[-2.5236e-01,  3.9307e-01,  1.5581e-01,  1.3284e+00],
         [ 8.1830e-01,  1.5279e+00,  3.1880e-01, -4.1388e-01],
         [-5.0392e-01,  1.2141e+00, -1.8075e+00,  4.7472e-02],
         ...,
         [-6.0203e-01,  4.5243e-01, -1.7072e-01, -2.5329e-01],
         [-7.9795e-01,  4.6026e-01,  2.4228e+00, -4.1313e-02],
         [-2.7699e-01, -7.7611e-01, -2.5134e+00, -7.2356e-01]],

        [[-1.9027e-02,  1.2823e+00,  1.7713e+00, -1.2226e+00],
         [ 5.6685e-01,  2.4027e-01,  1.2333e+00, -3.0240e-01],
         [-9.1078e-01,  7.4009e-03,  1.6436e+00, -1.9370e-01],
         ...,
         

In [6]:
peak_indices = output[1]
peak_indices

tensor([[ 4, 11, 18, 29, 37, 41, 48, 63],
        [ 7, 12, 17, 27, 34, 44, 51, 62],
        [ 1, 14, 21, 27, 34, 46, 52, 59],
        [ 7,  9, 21, 29, 32, 45, 48, 59],
        [ 4,  9, 22, 28, 39, 43, 52, 58],
        [ 3, 10, 16, 26, 32, 46, 51, 56],
        [ 7, 10, 19, 30, 38, 41, 53, 56],
        [ 1,  9, 18, 26, 38, 41, 52, 57],
        [ 3, 13, 21, 26, 32, 44, 51, 63],
        [ 0, 10, 22, 26, 36, 46, 51, 58]])

In [7]:
peak_indices.unsqueeze(-1).expand(-1,-1,4)

tensor([[[ 4,  4,  4,  4],
         [11, 11, 11, 11],
         [18, 18, 18, 18],
         [29, 29, 29, 29],
         [37, 37, 37, 37],
         [41, 41, 41, 41],
         [48, 48, 48, 48],
         [63, 63, 63, 63]],

        [[ 7,  7,  7,  7],
         [12, 12, 12, 12],
         [17, 17, 17, 17],
         [27, 27, 27, 27],
         [34, 34, 34, 34],
         [44, 44, 44, 44],
         [51, 51, 51, 51],
         [62, 62, 62, 62]],

        [[ 1,  1,  1,  1],
         [14, 14, 14, 14],
         [21, 21, 21, 21],
         [27, 27, 27, 27],
         [34, 34, 34, 34],
         [46, 46, 46, 46],
         [52, 52, 52, 52],
         [59, 59, 59, 59]],

        [[ 7,  7,  7,  7],
         [ 9,  9,  9,  9],
         [21, 21, 21, 21],
         [29, 29, 29, 29],
         [32, 32, 32, 32],
         [45, 45, 45, 45],
         [48, 48, 48, 48],
         [59, 59, 59, 59]],

        [[ 4,  4,  4,  4],
         [ 9,  9,  9,  9],
         [22, 22, 22, 22],
         [28, 28, 28, 28],
         [39, 39, 39

In [8]:
peak_indices.shape

torch.Size([10, 8])

In [9]:
torch.gather(input_[:,:,-1], 1, peak_indices).unsqueeze(-1).expand(-1,-1,4).shape

torch.Size([10, 8, 4])

In [10]:
input_[:,:,-1]

tensor([[-3.8037e-01, -1.4409e+00,  3.6781e-01, -3.1866e-01,  1.4484e+00,
         -6.7730e-01,  6.0127e-01, -1.2655e+00, -1.1730e+00, -2.6237e-01,
         -3.1045e-01,  1.7508e+00,  4.6951e-01,  9.5724e-01, -1.4991e-01,
          3.3491e-01,  5.3231e-02, -1.7610e+00,  7.3879e-01, -2.6760e+00,
         -2.0329e+00,  1.0827e-02, -1.1622e-01, -4.3586e-01, -1.8081e+00,
         -7.9936e-01, -3.1625e-01, -8.0669e-01, -1.2031e+00,  1.0413e+00,
         -7.4400e-01,  9.4321e-01,  2.9195e-01, -9.7320e-01, -3.1799e-01,
         -8.3720e-02,  9.7643e-01,  1.9484e+00, -1.7267e+00,  1.8561e+00,
         -6.0976e-02,  7.0732e-01,  3.3005e-01,  6.5367e-01,  1.1927e-01,
         -2.3844e-01, -6.9365e-01, -1.7980e-01,  1.1770e+00, -6.1377e-01,
         -1.0315e+00, -8.5601e-01, -4.2327e-01,  6.7735e-01,  4.1585e-01,
         -1.9643e+00, -1.7473e+00, -6.1493e-01, -4.0734e-02, -3.5726e-01,
         -2.7877e-01,  3.1244e-02,  3.9770e-01,  4.1022e-01],
        [ 6.9350e-01, -8.3307e-01, -1.0442e+00, -2

In [11]:
m(input_[:,:-1,-1] - input_[:,1:,-1])[1]

tensor([[ 4, 11, 18, 29, 37, 39, 54, 58],
        [ 5, 12, 17, 28, 34, 44, 53, 60],
        [ 5, 15, 15, 30, 34, 46, 52, 59],
        [ 7,  9, 21, 24, 32, 42, 48, 59],
        [ 4,  7, 22, 26, 39, 45, 50, 61],
        [ 5, 10, 16, 29, 32, 47, 47, 56],
        [ 7,  7, 19, 31, 31, 42, 54, 56],
        [ 4, 10, 23, 23, 31, 45, 52, 57],
        [ 0, 14, 18, 27, 32, 46, 51, 57],
        [ 3, 10, 22, 29, 36, 40, 51, 58]])

In [12]:
m = nn.AdaptiveMaxPool1d(8, return_indices=True)
input_ = torch.randn(10, 64, 5)
output = m(input_[:,:,-1])
peak_values, peak_indices = output
peak_indices

tensor([[ 0, 12, 16, 27, 35, 41, 51, 56],
        [ 6, 15, 23, 27, 32, 42, 55, 57],
        [ 5,  8, 20, 24, 37, 43, 48, 57],
        [ 3, 11, 16, 31, 35, 47, 53, 63],
        [ 3, 13, 19, 31, 37, 47, 51, 58],
        [ 0, 11, 21, 25, 36, 41, 48, 58],
        [ 1,  9, 20, 29, 32, 41, 50, 61],
        [ 1, 15, 17, 28, 37, 42, 50, 61],
        [ 6, 15, 16, 31, 36, 47, 52, 61],
        [ 2, 12, 22, 26, 35, 46, 48, 59]])

In [14]:
labels = torch.LongTensor([[ 8,  2,  5,  9,  2,  0,  9, 10],
                            [ 5,  6,  3, 12,  7, 15, 12, 11],
                            [ 0,  2,  1,  2,  8, 14, 10, 13],
                            [ 9,  1, 15, 10,  7, 13,  4,  1],
                            [10,  2, 10,  1, 10,  1,  5,  5],
                            [11, 16,  6, 15,  5, 15,  5, 12],
                            [10, 11,  8,  7,  7,  9, 13,  8],
                            [14,  4, 12, 11,  5, 10,  6,  2],
                            [15, 14,  2,  3, 15,  2, 10, 16],
                            [ 4, 15, 15, 15, 11, 16,  7,  3]])


lm_logits = torch.randn(10, 8, 17) # batch: 3, seq: 6, vocab_size:17
pred_label = torch.argmax(lm_logits[..., :, :], dim=2, keepdim=False)
pred_label

tensor([[ 5, 16,  5, 10, 15, 15, 16, 15],
        [16,  8,  2,  2, 14,  5, 15,  9],
        [ 2,  6, 13,  1, 15, 15,  8,  1],
        [ 9,  1, 14, 13,  5,  2,  0,  1],
        [16,  3,  4, 11, 12, 12, 12,  3],
        [11,  4, 11,  8,  2,  8,  8,  0],
        [ 6,  4,  0, 11,  5, 13,  2, 12],
        [ 3, 13, 10,  0,  9,  6,  7,  9],
        [10, 14,  4,  0, 10, 14,  1,  0],
        [15,  6,  5,  8,  5,  9, 13, 15]])

In [15]:
pred_label = torch.argmax(lm_logits[..., :, :], dim=2, keepdim=False)
loss_peak = torch.binary_cross_entropy_with_logits(peak_values, (pred_label == labels).float())

In [16]:
loss_peak

tensor([[1.4045, 1.8716, 0.1048, 1.4660, 0.7471, 1.5152, 1.6122, 1.3578],
        [1.9298, 1.1566, 2.2494, 1.2845, 2.4682, 1.8715, 1.3995, 1.1963],
        [1.7687, 2.7565, 1.1142, 1.2289, 1.3425, 1.2423, 1.7587, 1.4073],
        [0.3071, 0.1185, 1.0681, 1.0482, 1.7305, 1.5252, 1.6395, 0.1502],
        [1.1190, 2.2591, 1.1395, 1.6398, 2.3223, 1.7429, 1.4313, 1.4042],
        [0.3216, 0.8361, 1.5679, 1.5592, 1.3657, 0.9944, 1.5584, 1.5849],
        [2.1694, 0.8153, 1.1467, 1.6893, 1.6555, 1.9997, 1.1406, 1.8442],
        [1.2873, 0.8420, 1.9848, 1.4536, 1.4695, 1.2708, 2.7784, 1.8248],
        [1.4961, 0.1621, 2.0278, 0.7493, 1.8975, 0.9167, 1.7640, 0.7497],
        [1.1968, 0.9521, 1.6895, 2.0793, 1.5666, 1.3747, 1.8195, 0.9044]])

In [ ]:
peak_values

In [ ]:
(pred_label == labels).float()

In [50]:
lm_logits = torch.randn(10, 64, 5)
lm_logits.max(axis=2)

torch.return_types.max(
values=tensor([[ 0.9745,  0.6706,  0.7684,  0.7408,  2.8551,  2.4442,  0.5550,  1.3212,
          0.3334,  1.7347,  1.7006,  0.9743,  0.6944,  1.1692,  0.8869,  0.6143,
          1.4069,  0.8043,  1.9979,  1.2987,  0.4230,  1.3377,  0.6699,  1.2400,
          1.1509,  1.2615,  0.5953,  2.8560,  1.1580,  1.5226,  0.5852,  0.3671,
          0.5638,  0.5527,  0.4937,  1.7851,  1.6368,  1.2934,  1.8651, -0.0704,
          0.8625,  1.2517,  2.5961,  0.9198,  2.8899,  2.9901,  0.8609,  0.9424,
          0.3189,  0.3511,  0.3501,  1.9866,  1.1950,  0.2078,  0.9780,  0.9392,
          0.9844,  1.1953,  0.4109,  0.7613,  0.2776,  0.7725,  0.3451,  0.3508],
        [-0.0730,  0.7988,  0.9958,  1.4305,  0.7930,  0.6164, -0.5642,  2.7229,
          1.3831,  0.5765,  1.2455,  1.0611,  0.1133,  1.0686,  1.3430,  1.4013,
          0.6503,  1.1284,  0.8328,  1.2357,  1.6746,  1.3760,  1.6906,  1.1578,
          1.5226,  2.2274,  0.7553,  1.6615,  1.1365,  1.2940,  1.2718,  0.78

In [18]:
sim, _ = nn.functional.softmax(lm_logits, dim=-1).max(dim=-1)

In [19]:
adaPool = nn.AdaptiveMaxPool1d(8, return_indices=True)
peak_values, peak_indices = adaPool(sim)
peak_values, peak_indices

(tensor([[0.2298, 0.2237, 0.1806, 0.2741, 0.1664, 0.1391, 0.1543, 0.1691],
         [0.1354, 0.1579, 0.3011, 0.2627, 0.2351, 0.1617, 0.2248, 0.1234],
         [0.1998, 0.1513, 0.4888, 0.2503, 0.3447, 0.1898, 0.1751, 0.1926],
         [0.2829, 0.3271, 0.2426, 0.2297, 0.1943, 0.1208, 0.2027, 0.1935],
         [0.2947, 0.2885, 0.1398, 0.1813, 0.2162, 0.2102, 0.1742, 0.3733],
         [0.1365, 0.4949, 0.1827, 0.2374, 0.2388, 0.3275, 0.2886, 0.3632],
         [0.3551, 0.1695, 0.2136, 0.3067, 0.3219, 0.1887, 0.1495, 0.1463],
         [0.3327, 0.2434, 0.1993, 0.2348, 0.3439, 0.2452, 0.3621, 0.1526],
         [0.1734, 0.3103, 0.1786, 0.3588, 0.2217, 0.1905, 0.3474, 0.2389],
         [0.5486, 0.3124, 0.1964, 0.2016, 0.3889, 0.1131, 0.3223, 0.2308]]),
 tensor([[0, 1, 2, 3, 4, 5, 6, 7],
         [0, 1, 2, 3, 4, 5, 6, 7],
         [0, 1, 2, 3, 4, 5, 6, 7],
         [0, 1, 2, 3, 4, 5, 6, 7],
         [0, 1, 2, 3, 4, 5, 6, 7],
         [0, 1, 2, 3, 4, 5, 6, 7],
         [0, 1, 2, 3, 4, 5, 6, 7],
   

In [20]:
# torch.gather(lm_logits, 
#            1, 
#            peak_indices.unsqueeze(-1).expand(-1,-1,5))

In [21]:
sim, _ = nn.functional.softmax(lm_logits, dim=-1).max(dim=-1)
nn.functional.threshold(sim, 0.7, 0.0, inplace=False)[0]

tensor([0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
sim, _ = nn.functional.softmax(lm_logits, dim=-1).max(dim=-1)
sim = nn.functional.threshold(sim, 0.5, 0.0, inplace=False)
_, peak_indices = adaPool(sim)
peak_indices

tensor([[0, 1, 2, 3, 4, 5, 6, 7],
        [0, 1, 2, 3, 4, 5, 6, 7],
        [0, 1, 2, 3, 4, 5, 6, 7],
        [0, 1, 2, 3, 4, 5, 6, 7],
        [0, 1, 2, 3, 4, 5, 6, 7],
        [0, 1, 2, 3, 4, 5, 6, 7],
        [0, 1, 2, 3, 4, 5, 6, 7],
        [0, 1, 2, 3, 4, 5, 6, 7],
        [0, 1, 2, 3, 4, 5, 6, 7],
        [0, 1, 2, 3, 4, 5, 6, 7]])

In [44]:
labels = torch.LongTensor([[ 8,  2,  5,  9,  2,  0,  9, 10],
                            [ 5,  6,  3, 12,  7, 15, 12, 11],
                            [ 0,  2,  1,  2,  8, 14, 10, 13],
                            [ 9,  1, 15, 10,  7, 13,  4,  1],
                            [10,  2, 10,  1, 10,  1,  5,  5],
                            [11, 16,  6, 15,  5, 15,  5, 12],
                            [10, 11,  8,  7,  7,  9, 13,  8],
                            [14,  4, 12, 11,  5, 10,  6,  2],
                            [15, 14,  2,  3, 15,  2, 10, 16],
                            [ 4, 15, 15, 15, 11, 16,  7,  3]])
output_attention_mask = torch.ones((10, 8)).long()


hidden_states = torch.randn(10, 8, 17) # batch: 3, seq: 8, vocab_size:17

cos = nn.CosineSimilarity(dim=2, eps=1e-10)
peak = -cos(hidden_states[:,:-1,:], hidden_states[:,1:,:])


threshold = 0.0
_, peak_indices = adaPool(nn.functional.threshold(peak, threshold, -1.0, inplace=False))
peak_values = torch.gather(peak, 1, peak_indices)

attention_mask = torch.ones_like(peak_indices, dtype=torch.long)
word_embeddings = torch.gather(hidden_states, 
                               1, 
                               peak_indices.unsqueeze(-1).expand(-1,-1,8))


# ctc_loss doesn't support fp16
log_probs = nn.functional.log_softmax(lm_logits, dim=-1, dtype=torch.float32).transpose(0, 1)

# input_lengths for ctc_loss is defined from RNN peak detection
# this can be computed from attention_mask
input_lengths = (attention_mask > 0).sum(-1)

# assuming that padded tokens are filled with 'Ġ'
# unlike wav2vec we can get this information from given `output_attention_mask`
labels_mask = (output_attention_mask > 0)
target_lengths = labels_mask.sum(-1)
flattened_targets = labels.masked_select(labels_mask)

In [57]:
rand_arr = peak_max - torch.rand_like(peak) * (peak_max - peak_min)
rand_arr

tensor([[-0.9432, -0.8977,  0.5507, -0.6983,  0.5680,  0.9546, -0.9493],
        [ 0.5982, -0.2407,  0.9099, -0.5839,  0.3570,  0.6443,  0.2364],
        [ 0.6419, -0.2350, -0.6919,  0.3350, -0.3584,  0.3171, -0.8422],
        [-0.1181,  0.9154, -0.0295,  0.1802,  0.2820,  0.5055,  0.7339],
        [-0.5956, -0.7757, -0.7029, -0.8798,  0.4919,  0.3820,  0.1950],
        [ 0.7279, -0.3337, -0.0059,  0.1963, -0.0298, -0.8412,  0.0186],
        [-0.8601,  0.8751, -0.3137, -0.2510,  0.5285,  0.2301, -0.2327],
        [-0.3387, -0.7656, -0.5913,  0.5626, -0.9919,  0.3445,  0.9923],
        [ 0.0132, -0.6010, -0.9743, -0.0888, -0.7851,  0.3863,  0.2800],
        [-0.8826, -0.4796,  0.3370,  0.4261, -0.3293,  0.9938, -0.4268]])

In [58]:
torch.where(peak > threshold, peak, rand_arr)

tensor([[-0.9432,  0.0124,  0.1436,  0.0238,  0.5680,  0.9546, -0.9493],
        [ 0.5982, -0.2407,  0.2761, -0.5839,  0.0731,  0.6443,  0.2364],
        [ 0.6419,  0.3042,  0.0478,  0.3350,  0.3929,  0.3171,  0.3497],
        [-0.1181,  0.3853,  0.1831,  0.1802,  0.2820,  0.5055,  0.7339],
        [ 0.0465, -0.7757, -0.7029, -0.8798,  0.1183,  0.0150,  0.1950],
        [ 0.7279, -0.3337,  0.1123,  0.2518,  0.1331,  0.2686,  0.0612],
        [-0.8601,  0.4496, -0.3137,  0.2583,  0.0453,  0.2301, -0.2327],
        [ 0.1515,  0.3197,  0.3587,  0.0873, -0.9919,  0.1120,  0.9923],
        [ 0.0132,  0.1219,  0.1486, -0.0888,  0.2875,  0.3863,  0.2800],
        [-0.8826, -0.4796,  0.1007,  0.4261,  0.4980,  0.9938, -0.4268]])

In [67]:
torch.nn.ConstantPad2d((0,1,0,0), 220)(labels)

tensor([[  8,   2,   5,   9,   2,   0,   9,  10, 220],
        [  5,   6,   3,  12,   7,  15,  12,  11, 220],
        [  0,   2,   1,   2,   8,  14,  10,  13, 220],
        [  9,   1,  15,  10,   7,  13,   4,   1, 220],
        [ 10,   2,  10,   1,  10,   1,   5,   5, 220],
        [ 11,  16,   6,  15,   5,  15,   5,  12, 220],
        [ 10,  11,   8,   7,   7,   9,  13,   8, 220],
        [ 14,   4,  12,  11,   5,  10,   6,   2, 220],
        [ 15,  14,   2,   3,  15,   2,  10,  16, 220],
        [  4,  15,  15,  15,  11,  16,   7,   3, 220]])

In [49]:
nn.functional.threshold(peak, threshold, -1.0, inplace=False)

tensor([[-1.0000,  0.0124,  0.1436,  0.0238, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000,  0.2761, -1.0000,  0.0731, -1.0000, -1.0000],
        [-1.0000,  0.3042,  0.0478, -1.0000,  0.3929, -1.0000,  0.3497],
        [-1.0000,  0.3853,  0.1831, -1.0000, -1.0000, -1.0000, -1.0000],
        [ 0.0465, -1.0000, -1.0000, -1.0000,  0.1183,  0.0150, -1.0000],
        [-1.0000, -1.0000,  0.1123,  0.2518,  0.1331,  0.2686,  0.0612],
        [-1.0000,  0.4496, -1.0000,  0.2583,  0.0453, -1.0000, -1.0000],
        [ 0.1515,  0.3197,  0.3587,  0.0873, -1.0000,  0.1120, -1.0000],
        [-1.0000,  0.1219,  0.1486, -1.0000,  0.2875, -1.0000, -1.0000],
        [-1.0000, -1.0000,  0.1007, -1.0000,  0.4980, -1.0000, -1.0000]])

In [41]:
def ctcloss_reference(log_probs, targets, input_lengths, target_lengths, blank=0, reduction='mean'):
    input_lengths = torch.as_tensor(input_lengths, dtype=torch.long)
    target_lengths = torch.as_tensor(target_lengths, dtype=torch.long)
    dt = log_probs.dtype
    log_probs = log_probs.double()  # we need the accuracy as we are not in logspace
    targets = targets.long()
    cum_target_lengths = target_lengths.cumsum(0)
    losses = []
    for i in range(log_probs.size(1)):
        input_length = input_lengths[i].item()
        target_length = target_lengths[i].item()
        cum_target_length = cum_target_lengths[i].item()
        # ==========================================================================================================
        targets_prime = targets.new_full((2 * target_length + 1,), blank)
        if targets.dim() == 2:
            targets_prime[1::2] = targets[i, :target_length]
        else:
            targets_prime[1::2] = targets[cum_target_length - target_length:cum_target_length]
        # ==========================================================================================================
        probs = log_probs[:input_length, i].exp()
        # ==========================================================================================================
        alpha = log_probs.new_zeros((target_length * 2 + 1,))
        alpha[0] = probs[0, blank]
        alpha[1] = probs[0, targets_prime[1]]
        mask_third = (targets_prime[:-2] != targets_prime[2:])
        for t in range(1, input_length):
            alpha_next = alpha.clone()
            alpha_next[1:] += alpha[:-1]
            alpha_next[2:] += torch.where(mask_third, alpha[:-2], alpha.new_zeros(1))
            alpha = probs[t, targets_prime] * alpha_next
        # ==========================================================================================================
        print(alpha)
        
        losses.append(-alpha[-2:].sum().log()[None])
    output = torch.cat(losses, 0)
    if reduction == 'mean':
        return (output / target_lengths.to(dtype=output.dtype, device=output.device)).mean()
    elif reduction == 'sum':
        return output.sum()
    output = output.to(dt)
    return output

In [42]:
ctcloss_reference(log_probs, flattened_targets, input_lengths, target_lengths)

tensor([4.6589e-13, 1.6884e-11, 9.3202e-12, 3.2218e-10, 1.3834e-10, 1.5293e-10,
        5.2490e-10, 7.1434e-09, 3.2774e-09, 2.3075e-08, 4.9640e-09, 5.1073e-09,
        1.4381e-10, 4.1844e-10, 5.6487e-13, 2.3971e-12, 0.0000e+00],
       dtype=torch.float64)
tensor([4.8645e-13, 4.2530e-11, 6.4957e-11, 3.4620e-10, 1.7610e-10, 3.1341e-10,
        2.4851e-10, 2.1682e-10, 3.6141e-10, 5.3372e-09, 6.6471e-10, 5.8048e-09,
        4.0460e-10, 2.2505e-10, 2.1111e-12, 2.7577e-12, 0.0000e+00],
       dtype=torch.float64)
tensor([1.0181e-13, 8.1449e-13, 2.8507e-12, 3.4741e-11, 1.3328e-10, 1.2749e-09,
        3.1996e-10, 5.0960e-10, 1.0174e-09, 2.0520e-09, 2.3318e-09, 7.9496e-09,
        3.3101e-10, 2.4294e-10, 6.2279e-13, 7.6347e-13, 0.0000e+00],
       dtype=torch.float64)
tensor([3.1852e-11, 1.9054e-11, 7.7957e-10, 5.4160e-09, 1.7177e-08, 1.4399e-08,
        4.9155e-08, 6.6351e-08, 3.9770e-08, 2.2864e-07, 3.0181e-08, 1.2573e-08,
        2.2648e-09, 1.7391e-09, 1.0833e-11, 5.0595e-11, 0.0000e+00],


tensor(inf, dtype=torch.float64)

In [34]:
import os
from transformers import GPT2Tokenizer

In [35]:
cache_dir = "/data4/yoomcache"
model_cache_dir = os.path.join(cache_dir, 'huggingface')
data_cache_dir = os.path.join(cache_dir, 'datasets')
checkpoint_dir = os.path.join(cache_dir, 'checkpoint')

wav2vec_pretrained = "facebook/wav2vec2-base"
gpt_pretrained = "gpt2"

tokenizer = GPT2Tokenizer.from_pretrained(gpt_pretrained,
                                          cache_dir=model_cache_dir,)

In [ ]:
tokenizer.decoder[50256]

In [ ]:
lst = [379,287,319,281,329,355,326,838,284,1315,1105,416,642,807,554,351,257,1160,718,1478,767,1367,1511,1542,1467,604,286,422,340,1440,428,1115,2534,362,290,1936,357,352,2237,1679,1081,632,2319,318,706,513,2608,1596,407,307,860,2026,477,2242,1811,468,530,383,475,644,393,555,1114,3624,262,517,2681,678,787,373,2579,618,2048,651,770,734,818,1248,3439,3598,466,198,423,4570,510,314,3016,389,1675,2808,4747,317,460,1629,1867,3126,5193,4353,503,625,1002,550,464,345,1577,587,465,1987,1550,4153,4974,1234,836,5996,1318,6073,2310,4317,561,4019,887,347,5214,523,5441,1320,657,843,350,857,1802,939,655,5867,546,511,5433,925,481,327,1026,1011,1141,309,777,256,3412,5946,5137,467,7265,883,1406,1729,617,285,339,5846,3933,2263,356,6640,5014,612,1212,921,845,337,3261,4457,6337,275,6135,547,366,1972,1838,1649,1890,311,645,376,360,663,367,406,739,1892,2293,2953,1052,6298,611,7632,7175,279,300,2080,5365,7982,9796,703,371,534,597,775,1642,8190,7618,7600,269,867,4764,402,8646,743,1394,288,569,1595,8093,750,1342,5021,1029,2893,1402,1016,8454,878,6740,532,4101,6454,374,714,1858,399,780,679,8644,635,308,2148,370,881,661,1374,3478,412,3501,691,17,289,8699,1626,749,264,674,484,1877,810,1532,449,1244,11323,9773,479,7863,7337,616,1439,866,3574,474,3294,9225,1262,1588,8257,662,1757,8915,2773,9508,508,6885,2251,509,531,1263,2750,607,277,336,628,32,302,13454,940,2514,10053,1422,1111,1881,299,2753,588,9166,4900,1474,4930,1625,1722,572,1804,7323,7192,7930,19,3899,543,15495,2111,16677,5323,3607,16,832,9698,3268,656,8541,10083,2125,1231,1314,520,7724,609,13151,1719,981,2202,837,1392,8854,1107,911,717,4622,784,21,1718,5688,736,15143,18,20,3236,9193,8275,6702,772,765,2495,2025,1731,1415,471,440,2222,3271,1485,2063,3011,1065,5125,2061,1400,266,2795,890,442,2407,791,5357,2504,4858,3035,1135,3190,3938,10495,922,973,4047,575,1433,968,629,19048,23,13539,3237,9826,1157,9415,584,10190,9849,815,4650,2972,40,1064,1148,991,3633,1270,880,3336,3224,1639,4646,14956,621,2215,2383,1043,3125,2481,5729,781,852,2670,5199,6079,12279,19035,1537,649,3769,5390,22,15629,14436,10048,4874,5180,10460,1816,1828,2805,2211,4619,1218,1194,3152,978,427,2331,1282,790,2321,2327,1870,3260,2329,1495,3198,13037,4441,595,1682,1544,4632,1558,9775,9907,2075,9919,1688,3426,2921,18523,1954,19038,1593,892,17342,1119,13343,7473,5115,2067,2440,851,21409,2312,2011,1168,34,2078,19710,3737,583,1946,25500,6986,1239,10261,1983,33,2396,2627,20299,15349,3226,51,47,1737,8131,1366,1507,2208,3269,2623,7796,4366,3088,1238,764,25181,1355,7683,2932,938,640,1017,12168,606,6104,599,6547,18693,2793,2141,9661,760,1249,16003,4042,1022,1049,783,6635,1913,44,1139,3945,3181,1853,4995,8308,3132,5598,2408,2492,19409,3682,1222,2094,2548,15696,3267,1101,17501,16226,821,26,12713,2813,1903,7003,23871,2727,3578,1290,1957,49,553,2901,2266,20416,22986,21355,2682,1169,1088,2948,8684,751,1471,4955,3050,27829,1321,304,1388,1201,943,19884,7945,2718,900,3901,850,2949,21761,766,3700,19755,2192,1327,24,13374,673,5566,2900,21148,3098,37,20064,1680,526,1959,2091,2124,2102,3220,1178,3510,7650,2227,13,23134,1375,779,1821,18395,5179,3717,3977,987,]

for idx in lst:
    print(tokenizer.decoder[idx])

In [37]:
tokenizer.decoder

{0: '!',
 1: '"',
 2: '#',
 3: '$',
 4: '%',
 5: '&',
 6: "'",
 7: '(',
 8: ')',
 9: '*',
 10: '+',
 11: ',',
 12: '-',
 13: '.',
 14: '/',
 15: '0',
 16: '1',
 17: '2',
 18: '3',
 19: '4',
 20: '5',
 21: '6',
 22: '7',
 23: '8',
 24: '9',
 25: ':',
 26: ';',
 27: '<',
 28: '=',
 29: '>',
 30: '?',
 31: '@',
 32: 'A',
 33: 'B',
 34: 'C',
 35: 'D',
 36: 'E',
 37: 'F',
 38: 'G',
 39: 'H',
 40: 'I',
 41: 'J',
 42: 'K',
 43: 'L',
 44: 'M',
 45: 'N',
 46: 'O',
 47: 'P',
 48: 'Q',
 49: 'R',
 50: 'S',
 51: 'T',
 52: 'U',
 53: 'V',
 54: 'W',
 55: 'X',
 56: 'Y',
 57: 'Z',
 58: '[',
 59: '\\',
 60: ']',
 61: '^',
 62: '_',
 63: '`',
 64: 'a',
 65: 'b',
 66: 'c',
 67: 'd',
 68: 'e',
 69: 'f',
 70: 'g',
 71: 'h',
 72: 'i',
 73: 'j',
 74: 'k',
 75: 'l',
 76: 'm',
 77: 'n',
 78: 'o',
 79: 'p',
 80: 'q',
 81: 'r',
 82: 's',
 83: 't',
 84: 'u',
 85: 'v',
 86: 'w',
 87: 'x',
 88: 'y',
 89: 'z',
 90: '{',
 91: '|',
 92: '}',
 93: '~',
 94: '¡',
 95: '¢',
 96: '£',
 97: '¤',
 98: '¥',
 99: '¦',
 100: '§'