In [60]:
import torch
import torch.nn as nn
import numpy as np

In [61]:
rnn = nn.LSTM(10, 20, bidirectional=True)
input_ = torch.randn(6, 3, 10) # (seq_len, batch, input_state)
output, (hn, cn) = rnn(input_)

In [62]:
output.shape

torch.Size([6, 3, 40])

In [63]:
m = nn.AdaptiveMaxPool1d(8, return_indices=True)
input_ = torch.randn(10, 64, 5)
hidden_states, peak = input_[:,:,:-1], input_[:,:,-1]
peak_values, peak_indices = m(peak)

In [64]:
hidden_states

tensor([[[ 0.2000, -0.2965, -0.2208, -1.5311],
         [ 0.0141, -2.5344, -1.1507, -0.0047],
         [-0.2588, -0.2056, -1.9372, -1.1506],
         ...,
         [ 1.5177, -0.6383, -0.5786, -0.5134],
         [-1.3475,  0.3094,  0.7638, -0.5641],
         [ 0.9799,  1.2143,  1.4283, -0.4043]],

        [[ 0.0764,  1.0214,  0.0113,  0.3919],
         [ 0.2163, -0.3800, -0.4736, -2.7479],
         [ 0.4992,  0.4733,  1.7211,  0.3596],
         ...,
         [-1.7523, -0.9162,  1.5520,  0.6578],
         [ 0.0899,  0.8529, -0.6514,  2.0086],
         [-0.4912,  0.5996, -1.1437,  1.2587]],

        [[ 0.4594,  0.7425, -0.7260,  0.4576],
         [ 0.0401,  1.1417, -0.3344, -0.8563],
         [-0.6201,  0.6714, -1.4530, -1.8778],
         ...,
         [ 0.0984, -0.2239,  1.4361,  0.1292],
         [-0.2430,  1.5821, -0.2780,  1.2236],
         [-0.6219, -0.5811, -1.5943,  0.6945]],

        ...,

        [[-1.2568, -0.3326,  0.0289, -1.5400],
         [-0.0519,  0.6400,  1.8838, -0.8912]

In [65]:
peak.size()

torch.Size([10, 64])

In [66]:
peak_indices

tensor([[ 6, 13, 18, 24, 34, 43, 55, 63],
        [ 2,  9, 17, 31, 37, 45, 48, 56],
        [ 2, 15, 22, 27, 33, 46, 52, 62],
        [ 0,  9, 21, 31, 37, 42, 55, 59],
        [ 5, 15, 17, 31, 34, 43, 55, 58],
        [ 1, 10, 16, 29, 39, 45, 51, 59],
        [ 5, 11, 19, 25, 36, 43, 54, 63],
        [ 7, 12, 23, 25, 38, 40, 48, 61],
        [ 2, 14, 17, 27, 34, 42, 51, 56],
        [ 6, 12, 19, 30, 37, 42, 54, 61]])

In [67]:
peak_indices.unsqueeze(-1).expand(-1,-1,4)

tensor([[[ 6,  6,  6,  6],
         [13, 13, 13, 13],
         [18, 18, 18, 18],
         [24, 24, 24, 24],
         [34, 34, 34, 34],
         [43, 43, 43, 43],
         [55, 55, 55, 55],
         [63, 63, 63, 63]],

        [[ 2,  2,  2,  2],
         [ 9,  9,  9,  9],
         [17, 17, 17, 17],
         [31, 31, 31, 31],
         [37, 37, 37, 37],
         [45, 45, 45, 45],
         [48, 48, 48, 48],
         [56, 56, 56, 56]],

        [[ 2,  2,  2,  2],
         [15, 15, 15, 15],
         [22, 22, 22, 22],
         [27, 27, 27, 27],
         [33, 33, 33, 33],
         [46, 46, 46, 46],
         [52, 52, 52, 52],
         [62, 62, 62, 62]],

        [[ 0,  0,  0,  0],
         [ 9,  9,  9,  9],
         [21, 21, 21, 21],
         [31, 31, 31, 31],
         [37, 37, 37, 37],
         [42, 42, 42, 42],
         [55, 55, 55, 55],
         [59, 59, 59, 59]],

        [[ 5,  5,  5,  5],
         [15, 15, 15, 15],
         [17, 17, 17, 17],
         [31, 31, 31, 31],
         [34, 34, 34

In [68]:
torch.where(peak >= peak_values.min(dim=1)[0].unsqueeze(-1).expand(-1,peak.size(1)), 1, 0)

tensor([[0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
         1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
         0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1],
        [0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
         1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
         1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
         0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
         0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
         0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
         1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1],
        [0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 

In [69]:
attention_mask = torch.where(peak >= peak_values.min(dim=1)[0].unsqueeze(-1).expand(-1,peak.size(1)), 1, 0)
nn.functional.pad(attention_mask, (0,1,0,0), mode='constant', value=0)

tensor([[0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
         1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
         0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0],
        [0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
         1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
         1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
         0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
         0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
         0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
         1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0],
        [0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 

In [70]:
m(input_[:,:-1,-1] - input_[:,1:,-1])[1]

tensor([[ 6, 13, 22, 24, 32, 43, 49, 59],
        [ 2, 12, 18, 31, 31, 45, 48, 56],
        [ 7,  7, 15, 27, 33, 44, 52, 59],
        [ 0, 11, 21, 31, 32, 42, 50, 61],
        [ 6, 12, 15, 25, 36, 43, 53, 58],
        [ 6, 12, 16, 26, 37, 45, 54, 56],
        [ 0, 11, 20, 25, 36, 43, 49, 58],
        [ 0, 12, 23, 23, 33, 42, 49, 61],
        [ 2, 14, 17, 27, 34, 40, 51, 56],
        [ 6, 12, 19, 30, 39, 42, 54, 61]])

In [71]:
m = nn.AdaptiveMaxPool1d(8, return_indices=True)
input_ = torch.randn(10, 64, 5)
output = m(input_[:,:,-1])
peak_values, peak_indices = output
peak_indices

tensor([[ 3,  8, 20, 24, 33, 42, 50, 58],
        [ 3, 14, 19, 28, 37, 45, 55, 62],
        [ 1, 11, 23, 31, 32, 47, 51, 59],
        [ 6, 11, 23, 28, 35, 46, 49, 56],
        [ 5, 11, 22, 31, 36, 42, 55, 61],
        [ 0,  9, 20, 26, 36, 41, 50, 59],
        [ 3, 14, 23, 24, 35, 44, 54, 56],
        [ 7, 12, 22, 30, 38, 41, 55, 61],
        [ 2, 12, 16, 28, 35, 47, 50, 60],
        [ 1, 12, 23, 31, 32, 42, 53, 59]])

In [72]:
labels = torch.LongTensor([[ 8,  2,  5,  9,  2,  0,  9, 10],
                            [ 5,  6,  3, 12,  7, 15, 12, 11],
                            [ 0,  2,  1,  2,  8, 14, 10, 13],
                            [ 9,  1, 15, 10,  7, 13,  4,  1],
                            [10,  2, 10,  1, 10,  1,  5,  5],
                            [11, 16,  6, 15,  5, 15,  5, 12],
                            [10, 11,  8,  7,  7,  9, 13,  8],
                            [14,  4, 12, 11,  5, 10,  6,  2],
                            [15, 14,  2,  3, 15,  2, 10, 16],
                            [ 4, 15, 15, 15, 11, 16,  7,  3]])


lm_logits = torch.randn(10, 8, 17) # batch: 3, seq: 6, vocab_size:17
pred_label = torch.argmax(lm_logits[..., :, :], dim=2, keepdim=False)
pred_label

tensor([[ 1,  8,  5,  1, 13,  2,  3,  5],
        [ 4,  4,  3, 14,  4,  3,  9, 11],
        [ 4,  9,  3,  2,  1,  2, 12,  8],
        [12, 16, 14,  5, 15,  6, 13, 16],
        [10, 16,  1, 12,  1,  9,  9,  3],
        [14,  3,  4,  3,  3,  7,  4, 11],
        [14, 12,  3, 13, 14, 15, 10,  1],
        [ 9,  1,  3, 16,  0, 10,  4,  7],
        [ 3, 16,  7, 15, 11, 11,  1,  1],
        [11,  5,  6, 12, 12, 15, 10, 13]])

In [73]:
pred_label = torch.argmax(lm_logits[..., :, :], dim=2, keepdim=False)
loss_peak = torch.binary_cross_entropy_with_logits(peak_values, (pred_label == labels).float())

In [74]:
loss_peak

tensor([[1.5564, 1.0822, 0.4509, 1.5788, 1.2846, 2.0580, 1.9542, 0.8372],
        [1.5642, 1.9789, 0.2242, 1.8752, 1.5667, 1.0829, 1.8913, 0.2867],
        [0.9234, 2.1745, 1.8493, 0.4190, 1.0391, 1.9315, 1.5220, 0.9571],
        [1.8056, 2.6107, 1.9748, 1.8438, 2.0410, 1.5962, 2.3993, 2.3716],
        [0.1479, 1.7636, 1.4761, 2.6316, 1.4447, 1.2865, 1.8241, 1.7405],
        [1.3389, 2.1617, 2.5268, 1.3026, 1.3961, 0.9127, 1.3415, 1.1022],
        [1.1832, 1.2295, 1.3042, 2.6070, 1.1620, 1.6475, 2.5005, 2.3029],
        [2.2742, 1.3788, 1.9834, 1.3300, 1.7606, 0.1179, 1.7884, 0.9628],
        [1.0106, 2.2729, 1.1003, 2.0958, 1.9864, 1.8831, 2.6114, 2.8641],
        [1.3624, 1.9362, 0.7995, 1.0764, 1.7285, 1.7351, 1.7551, 1.0702]])

In [75]:
peak_values

tensor([[1.3195, 0.6684, 0.5625, 1.3478, 0.9606, 1.9214, 1.8014, 0.2700],
        [1.3294, 1.8301, 1.3810, 1.7087, 1.3325, 0.6695, 1.7278, 1.1024],
        [0.4172, 2.0538, 1.6781, 0.6531, 0.6025, 1.7749, 1.2758, 0.4726],
        [1.6260, 2.5344, 1.8254, 1.6715, 1.9019, 1.3698, 2.3042, 2.2736],
        [1.8360, 1.5756, 1.2166, 2.5569, 1.1758, 0.9633, 1.6481, 1.5476],
        [1.0349, 2.0394, 2.4435, 0.9855, 1.1117, 0.3995, 1.0384, 0.6985],
        [0.8175, 0.8836, 0.9875, 2.5304, 0.7867, 1.4337, 2.4149, 2.1976],
        [2.1656, 1.0887, 1.8354, 1.0228, 1.5720, 2.0787, 1.6054, 0.4818],
        [0.5580, 2.1642, 0.6957, 1.9646, 1.8388, 1.7181, 2.5351, 2.8054],
        [1.0666, 1.7804, 0.2025, 0.6596, 1.5330, 1.5411, 1.5652, 0.6502]])

In [76]:
(pred_label == labels).float()

tensor([[0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

In [77]:
lm_logits = torch.randn(10, 64, 5)
lm_logits.max(axis=2)

torch.return_types.max(
values=tensor([[-0.3084,  1.6866,  1.6117,  0.9698,  2.0495,  1.3440,  0.9888,  1.4596,
          1.4429,  0.8147,  0.0976,  2.0972,  1.5441,  1.0902,  1.5217,  1.2635,
         -0.1483,  1.7322,  1.7627,  1.8031,  0.7477,  1.0680,  1.1418,  0.8647,
          0.6536,  1.4081,  0.8071,  1.0107,  1.9388,  1.9420,  1.0947,  0.1482,
          0.6699,  0.9300,  1.7979,  1.6813,  0.6532,  1.6796,  1.7580,  1.1983,
          0.9506,  2.0081,  0.7722, -0.1044,  1.0084,  1.2638,  2.3838,  1.7721,
          2.1871,  1.0712,  0.7853,  0.7914,  1.8280,  1.2325,  0.7129,  0.7750,
          1.7624,  0.3088,  1.0490,  0.4446,  0.6047,  0.2575,  0.4435,  1.2036],
        [ 1.0393,  1.0769,  0.5378,  2.7197,  0.5459,  0.4998,  0.2838,  0.7519,
          0.2911,  0.9053,  1.5468,  0.5858,  1.0000,  1.0970,  1.0580,  0.9960,
          0.8111,  0.6581,  0.5260,  0.7965, -0.1437,  2.2750,  1.7818,  1.0233,
          1.1709,  1.0988,  0.1643,  0.7146, -0.6394,  1.7253,  1.9522,  0.38

In [78]:
sim, _ = nn.functional.softmax(lm_logits, dim=-1).max(dim=-1)

In [79]:
adaPool = nn.AdaptiveMaxPool1d(8, return_indices=True)
peak_values, peak_indices = adaPool(sim)
peak_values, peak_indices

(tensor([[0.6371, 0.7113, 0.6539, 0.6658, 0.4832, 0.6810, 0.6999, 0.4940],
         [0.6886, 0.6154, 0.6660, 0.5265, 0.5434, 0.6740, 0.7728, 0.8885],
         [0.7297, 0.5439, 0.6158, 0.7085, 0.6764, 0.6120, 0.5101, 0.6644],
         [0.8776, 0.5991, 0.4408, 0.8313, 0.5794, 0.6011, 0.6572, 0.6787],
         [0.5990, 0.5281, 0.6563, 0.8818, 0.5611, 0.6509, 0.8271, 0.7608],
         [0.5532, 0.7141, 0.7272, 0.7706, 0.6315, 0.6421, 0.6944, 0.6903],
         [0.6303, 0.5447, 0.6154, 0.7218, 0.6062, 0.7099, 0.5324, 0.7870],
         [0.7313, 0.6444, 0.6772, 0.6342, 0.8451, 0.7391, 0.6177, 0.6599],
         [0.4756, 0.6944, 0.5924, 0.7056, 0.5227, 0.7739, 0.5577, 0.5017],
         [0.5419, 0.7659, 0.8067, 0.7036, 0.7211, 0.5651, 0.4744, 0.5982]]),
 tensor([[ 1, 14, 19, 28, 35, 41, 48, 56],
         [ 3, 10, 21, 30, 34, 42, 51, 57],
         [ 0, 13, 20, 28, 38, 44, 50, 61],
         [ 6, 12, 22, 24, 33, 41, 48, 56],
         [ 2, 10, 19, 24, 32, 45, 51, 62],
         [ 6, 11, 16, 26, 33, 43,

In [80]:
# torch.gather(lm_logits, 
#            1, 
#            peak_indices.unsqueeze(-1).expand(-1,-1,5))

In [81]:
sim, _ = nn.functional.softmax(lm_logits, dim=-1).max(dim=-1)
nn.functional.threshold(sim, 0.7, 0.0, inplace=False)[0]

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.7113, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000])

In [82]:
sim, _ = nn.functional.softmax(lm_logits, dim=-1).max(dim=-1)
sim = nn.functional.threshold(sim, 0.5, 0.0, inplace=False)
_, peak_indices = adaPool(sim)
peak_indices

tensor([[ 1, 14, 19, 28, 32, 41, 48, 56],
        [ 3, 10, 21, 30, 34, 42, 51, 57],
        [ 0, 13, 20, 28, 38, 44, 50, 61],
        [ 6, 12, 16, 24, 33, 41, 48, 56],
        [ 2, 10, 19, 24, 32, 45, 51, 62],
        [ 6, 11, 16, 26, 33, 43, 51, 58],
        [ 6, 13, 16, 25, 37, 43, 48, 60],
        [ 2, 10, 22, 26, 35, 42, 50, 63],
        [ 0, 14, 19, 26, 38, 42, 51, 58],
        [ 0, 11, 19, 29, 32, 40, 48, 63]])

In [87]:
labels = torch.LongTensor([[ 8,  2,  5,  9,  2,  0,  9, 10],
                            [ 5,  6,  3, 12,  7, 15, 12, 11],
                            [ 0,  2,  1,  2,  8, 14, 10, 13],
                            [ 9,  1, 15, 10,  7, 13,  4,  1],
                            [10,  2, 10,  1, 10,  1,  5,  5],
                            [11, 16,  6, 15,  5, 15,  5, 12],
                            [10, 11,  8,  7,  7,  9, 13,  8],
                            [14,  4, 12, 11,  5, 10,  6,  2],
                            [15, 14,  2,  3, 15,  2, 10, 16],
                            [ 4, 15, 15, 15, 11, 16,  7,  3]])
output_attention_mask = torch.ones((10, 8)).long()


hidden_states = torch.randn(10, 8, 17) # batch: 3, seq: 8, vocab_size:17

cos = nn.CosineSimilarity(dim=2, eps=1e-10)
peak = -cos(hidden_states[:,:-1,:], hidden_states[:,1:,:])


peak_min, threshold, peak_max = -1.0, -0.25, 1.0
_, peak_indices = adaPool(nn.functional.threshold(peak, threshold, -1.0, inplace=False))
peak_values = torch.gather(peak, 1, peak_indices)

attention_mask = torch.ones_like(peak_indices, dtype=torch.long)
word_embeddings = torch.gather(hidden_states, 
                               1, 
                               peak_indices.unsqueeze(-1).expand(-1,-1,8))


# ctc_loss doesn't support fp16
log_probs = nn.functional.log_softmax(lm_logits, dim=-1, dtype=torch.float32).transpose(0, 1)

# input_lengths for ctc_loss is defined from RNN peak detection
# this can be computed from attention_mask
input_lengths = (attention_mask > 0).sum(-1)

# assuming that padded tokens are filled with 'Ġ'
# unlike wav2vec we can get this information from given `output_attention_mask`
labels_mask = (output_attention_mask > 0)
target_lengths = labels_mask.sum(-1)
flattened_targets = labels.masked_select(labels_mask)

In [88]:
rand_arr = peak_max - torch.rand_like(peak) * (peak_max - peak_min)
rand_arr

tensor([[-0.3548,  0.8480,  0.4208, -0.6502,  0.9330, -0.7001,  0.3314],
        [-0.1190, -0.0275, -0.7941, -0.4843,  0.2176,  0.3056, -0.9596],
        [ 0.6437, -0.3768,  0.9237, -0.1813,  0.0356, -0.8298,  0.6685],
        [ 0.6288,  0.4490, -0.8141, -0.2252,  0.6019, -0.7261,  0.8757],
        [ 0.3766,  0.8873,  0.1857,  0.3498,  0.8676,  0.6045, -0.4825],
        [-0.9401,  0.9193, -0.3107,  0.6471, -0.6423,  0.4934,  0.4392],
        [ 0.3144,  0.5935, -0.0865,  0.5704, -0.6300, -0.1896, -0.7666],
        [ 0.5708, -0.9884, -0.7868, -0.4532,  0.1233, -0.1323, -0.9159],
        [-0.0072,  0.7856,  0.9706,  0.7489,  0.9466, -0.9137, -0.3940],
        [ 0.7473, -0.6074,  0.1333, -0.4574, -0.1543,  0.1005,  0.0726]])

In [91]:
torch.where(peak > threshold, peak, rand_arr)

torch.float32

In [99]:
torch.where(peak > threshold, peak, torch.tensor(threshold))

tensor([[ 0.1229, -0.0396,  0.3921, -0.2500,  0.3867,  0.0039, -0.0321],
        [-0.0282, -0.2500,  0.3161,  0.4024,  0.0742, -0.2500, -0.1672],
        [-0.0058, -0.0945,  0.2487, -0.1499,  0.1145,  0.2011, -0.0524],
        [ 0.1907, -0.0431,  0.4695,  0.2039,  0.1798,  0.0318,  0.0404],
        [ 0.2051,  0.1577, -0.1642,  0.0759,  0.2468, -0.1419, -0.2500],
        [-0.2324,  0.4086,  0.4125, -0.1460,  0.0885,  0.2838,  0.6216],
        [-0.1122,  0.0922, -0.1890, -0.0562, -0.0470, -0.0623, -0.0124],
        [ 0.1594,  0.0877, -0.2289, -0.0031, -0.0841,  0.1639,  0.0617],
        [ 0.0471,  0.0532, -0.0881, -0.0063,  0.0418,  0.2988, -0.2500],
        [-0.1040,  0.2068, -0.2350, -0.2285,  0.3139,  0.0658, -0.2418]])

In [67]:
torch.nn.ConstantPad2d((0,1,0,0), 220)(labels)

tensor([[  8,   2,   5,   9,   2,   0,   9,  10, 220],
        [  5,   6,   3,  12,   7,  15,  12,  11, 220],
        [  0,   2,   1,   2,   8,  14,  10,  13, 220],
        [  9,   1,  15,  10,   7,  13,   4,   1, 220],
        [ 10,   2,  10,   1,  10,   1,   5,   5, 220],
        [ 11,  16,   6,  15,   5,  15,   5,  12, 220],
        [ 10,  11,   8,   7,   7,   9,  13,   8, 220],
        [ 14,   4,  12,  11,   5,  10,   6,   2, 220],
        [ 15,  14,   2,   3,  15,   2,  10,  16, 220],
        [  4,  15,  15,  15,  11,  16,   7,   3, 220]])

In [49]:
nn.functional.threshold(peak, threshold, -1.0, inplace=False)

tensor([[-1.0000,  0.0124,  0.1436,  0.0238, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000,  0.2761, -1.0000,  0.0731, -1.0000, -1.0000],
        [-1.0000,  0.3042,  0.0478, -1.0000,  0.3929, -1.0000,  0.3497],
        [-1.0000,  0.3853,  0.1831, -1.0000, -1.0000, -1.0000, -1.0000],
        [ 0.0465, -1.0000, -1.0000, -1.0000,  0.1183,  0.0150, -1.0000],
        [-1.0000, -1.0000,  0.1123,  0.2518,  0.1331,  0.2686,  0.0612],
        [-1.0000,  0.4496, -1.0000,  0.2583,  0.0453, -1.0000, -1.0000],
        [ 0.1515,  0.3197,  0.3587,  0.0873, -1.0000,  0.1120, -1.0000],
        [-1.0000,  0.1219,  0.1486, -1.0000,  0.2875, -1.0000, -1.0000],
        [-1.0000, -1.0000,  0.1007, -1.0000,  0.4980, -1.0000, -1.0000]])

In [41]:
def ctcloss_reference(log_probs, targets, input_lengths, target_lengths, blank=0, reduction='mean'):
    input_lengths = torch.as_tensor(input_lengths, dtype=torch.long)
    target_lengths = torch.as_tensor(target_lengths, dtype=torch.long)
    dt = log_probs.dtype
    log_probs = log_probs.double()  # we need the accuracy as we are not in logspace
    targets = targets.long()
    cum_target_lengths = target_lengths.cumsum(0)
    losses = []
    for i in range(log_probs.size(1)):
        input_length = input_lengths[i].item()
        target_length = target_lengths[i].item()
        cum_target_length = cum_target_lengths[i].item()
        # ==========================================================================================================
        targets_prime = targets.new_full((2 * target_length + 1,), blank)
        if targets.dim() == 2:
            targets_prime[1::2] = targets[i, :target_length]
        else:
            targets_prime[1::2] = targets[cum_target_length - target_length:cum_target_length]
        # ==========================================================================================================
        probs = log_probs[:input_length, i].exp()
        # ==========================================================================================================
        alpha = log_probs.new_zeros((target_length * 2 + 1,))
        alpha[0] = probs[0, blank]
        alpha[1] = probs[0, targets_prime[1]]
        mask_third = (targets_prime[:-2] != targets_prime[2:])
        for t in range(1, input_length):
            alpha_next = alpha.clone()
            alpha_next[1:] += alpha[:-1]
            alpha_next[2:] += torch.where(mask_third, alpha[:-2], alpha.new_zeros(1))
            alpha = probs[t, targets_prime] * alpha_next
        # ==========================================================================================================
        print(alpha)
        
        losses.append(-alpha[-2:].sum().log()[None])
    output = torch.cat(losses, 0)
    if reduction == 'mean':
        return (output / target_lengths.to(dtype=output.dtype, device=output.device)).mean()
    elif reduction == 'sum':
        return output.sum()
    output = output.to(dt)
    return output

In [42]:
ctcloss_reference(log_probs, flattened_targets, input_lengths, target_lengths)

tensor([4.6589e-13, 1.6884e-11, 9.3202e-12, 3.2218e-10, 1.3834e-10, 1.5293e-10,
        5.2490e-10, 7.1434e-09, 3.2774e-09, 2.3075e-08, 4.9640e-09, 5.1073e-09,
        1.4381e-10, 4.1844e-10, 5.6487e-13, 2.3971e-12, 0.0000e+00],
       dtype=torch.float64)
tensor([4.8645e-13, 4.2530e-11, 6.4957e-11, 3.4620e-10, 1.7610e-10, 3.1341e-10,
        2.4851e-10, 2.1682e-10, 3.6141e-10, 5.3372e-09, 6.6471e-10, 5.8048e-09,
        4.0460e-10, 2.2505e-10, 2.1111e-12, 2.7577e-12, 0.0000e+00],
       dtype=torch.float64)
tensor([1.0181e-13, 8.1449e-13, 2.8507e-12, 3.4741e-11, 1.3328e-10, 1.2749e-09,
        3.1996e-10, 5.0960e-10, 1.0174e-09, 2.0520e-09, 2.3318e-09, 7.9496e-09,
        3.3101e-10, 2.4294e-10, 6.2279e-13, 7.6347e-13, 0.0000e+00],
       dtype=torch.float64)
tensor([3.1852e-11, 1.9054e-11, 7.7957e-10, 5.4160e-09, 1.7177e-08, 1.4399e-08,
        4.9155e-08, 6.6351e-08, 3.9770e-08, 2.2864e-07, 3.0181e-08, 1.2573e-08,
        2.2648e-09, 1.7391e-09, 1.0833e-11, 5.0595e-11, 0.0000e+00],


tensor(inf, dtype=torch.float64)

In [34]:
import os
from transformers import GPT2Tokenizer

In [35]:
cache_dir = "/data4/yoomcache"
model_cache_dir = os.path.join(cache_dir, 'huggingface')
data_cache_dir = os.path.join(cache_dir, 'datasets')
checkpoint_dir = os.path.join(cache_dir, 'checkpoint')

wav2vec_pretrained = "facebook/wav2vec2-base"
gpt_pretrained = "gpt2"

tokenizer = GPT2Tokenizer.from_pretrained(gpt_pretrained,
                                          cache_dir=model_cache_dir,)

In [ ]:
tokenizer.decoder[50256]

In [ ]:
lst = [379,287,319,281,329,355,326,838,284,1315,1105,416,642,807,554,351,257,1160,718,1478,767,1367,1511,1542,1467,604,286,422,340,1440,428,1115,2534,362,290,1936,357,352,2237,1679,1081,632,2319,318,706,513,2608,1596,407,307,860,2026,477,2242,1811,468,530,383,475,644,393,555,1114,3624,262,517,2681,678,787,373,2579,618,2048,651,770,734,818,1248,3439,3598,466,198,423,4570,510,314,3016,389,1675,2808,4747,317,460,1629,1867,3126,5193,4353,503,625,1002,550,464,345,1577,587,465,1987,1550,4153,4974,1234,836,5996,1318,6073,2310,4317,561,4019,887,347,5214,523,5441,1320,657,843,350,857,1802,939,655,5867,546,511,5433,925,481,327,1026,1011,1141,309,777,256,3412,5946,5137,467,7265,883,1406,1729,617,285,339,5846,3933,2263,356,6640,5014,612,1212,921,845,337,3261,4457,6337,275,6135,547,366,1972,1838,1649,1890,311,645,376,360,663,367,406,739,1892,2293,2953,1052,6298,611,7632,7175,279,300,2080,5365,7982,9796,703,371,534,597,775,1642,8190,7618,7600,269,867,4764,402,8646,743,1394,288,569,1595,8093,750,1342,5021,1029,2893,1402,1016,8454,878,6740,532,4101,6454,374,714,1858,399,780,679,8644,635,308,2148,370,881,661,1374,3478,412,3501,691,17,289,8699,1626,749,264,674,484,1877,810,1532,449,1244,11323,9773,479,7863,7337,616,1439,866,3574,474,3294,9225,1262,1588,8257,662,1757,8915,2773,9508,508,6885,2251,509,531,1263,2750,607,277,336,628,32,302,13454,940,2514,10053,1422,1111,1881,299,2753,588,9166,4900,1474,4930,1625,1722,572,1804,7323,7192,7930,19,3899,543,15495,2111,16677,5323,3607,16,832,9698,3268,656,8541,10083,2125,1231,1314,520,7724,609,13151,1719,981,2202,837,1392,8854,1107,911,717,4622,784,21,1718,5688,736,15143,18,20,3236,9193,8275,6702,772,765,2495,2025,1731,1415,471,440,2222,3271,1485,2063,3011,1065,5125,2061,1400,266,2795,890,442,2407,791,5357,2504,4858,3035,1135,3190,3938,10495,922,973,4047,575,1433,968,629,19048,23,13539,3237,9826,1157,9415,584,10190,9849,815,4650,2972,40,1064,1148,991,3633,1270,880,3336,3224,1639,4646,14956,621,2215,2383,1043,3125,2481,5729,781,852,2670,5199,6079,12279,19035,1537,649,3769,5390,22,15629,14436,10048,4874,5180,10460,1816,1828,2805,2211,4619,1218,1194,3152,978,427,2331,1282,790,2321,2327,1870,3260,2329,1495,3198,13037,4441,595,1682,1544,4632,1558,9775,9907,2075,9919,1688,3426,2921,18523,1954,19038,1593,892,17342,1119,13343,7473,5115,2067,2440,851,21409,2312,2011,1168,34,2078,19710,3737,583,1946,25500,6986,1239,10261,1983,33,2396,2627,20299,15349,3226,51,47,1737,8131,1366,1507,2208,3269,2623,7796,4366,3088,1238,764,25181,1355,7683,2932,938,640,1017,12168,606,6104,599,6547,18693,2793,2141,9661,760,1249,16003,4042,1022,1049,783,6635,1913,44,1139,3945,3181,1853,4995,8308,3132,5598,2408,2492,19409,3682,1222,2094,2548,15696,3267,1101,17501,16226,821,26,12713,2813,1903,7003,23871,2727,3578,1290,1957,49,553,2901,2266,20416,22986,21355,2682,1169,1088,2948,8684,751,1471,4955,3050,27829,1321,304,1388,1201,943,19884,7945,2718,900,3901,850,2949,21761,766,3700,19755,2192,1327,24,13374,673,5566,2900,21148,3098,37,20064,1680,526,1959,2091,2124,2102,3220,1178,3510,7650,2227,13,23134,1375,779,1821,18395,5179,3717,3977,987,]

for idx in lst:
    print(tokenizer.decoder[idx])

In [37]:
tokenizer.decoder

{0: '!',
 1: '"',
 2: '#',
 3: '$',
 4: '%',
 5: '&',
 6: "'",
 7: '(',
 8: ')',
 9: '*',
 10: '+',
 11: ',',
 12: '-',
 13: '.',
 14: '/',
 15: '0',
 16: '1',
 17: '2',
 18: '3',
 19: '4',
 20: '5',
 21: '6',
 22: '7',
 23: '8',
 24: '9',
 25: ':',
 26: ';',
 27: '<',
 28: '=',
 29: '>',
 30: '?',
 31: '@',
 32: 'A',
 33: 'B',
 34: 'C',
 35: 'D',
 36: 'E',
 37: 'F',
 38: 'G',
 39: 'H',
 40: 'I',
 41: 'J',
 42: 'K',
 43: 'L',
 44: 'M',
 45: 'N',
 46: 'O',
 47: 'P',
 48: 'Q',
 49: 'R',
 50: 'S',
 51: 'T',
 52: 'U',
 53: 'V',
 54: 'W',
 55: 'X',
 56: 'Y',
 57: 'Z',
 58: '[',
 59: '\\',
 60: ']',
 61: '^',
 62: '_',
 63: '`',
 64: 'a',
 65: 'b',
 66: 'c',
 67: 'd',
 68: 'e',
 69: 'f',
 70: 'g',
 71: 'h',
 72: 'i',
 73: 'j',
 74: 'k',
 75: 'l',
 76: 'm',
 77: 'n',
 78: 'o',
 79: 'p',
 80: 'q',
 81: 'r',
 82: 's',
 83: 't',
 84: 'u',
 85: 'v',
 86: 'w',
 87: 'x',
 88: 'y',
 89: 'z',
 90: '{',
 91: '|',
 92: '}',
 93: '~',
 94: '¡',
 95: '¢',
 96: '£',
 97: '¤',
 98: '¥',
 99: '¦',
 100: '§'

In [104]:
encoder_layer = nn.TransformerEncoderLayer(d_model=256, nhead=8)
src = torch.rand(10, 32, 256)
out = encoder_layer(src)

In [105]:
out.shape

torch.Size([10, 32, 256])